### ISSUE TITLE
Update mongodb drivers to 2.2.0

### ISSUE THREAD

**Issue by judowalker** [MarkCBB/MongoDB-ASP.NET-Session-State-Store#1]
Can you update the mongo db drivers to the latest version (2.2.0)?

**Comment by MarkCBB** [comment]
Yes, I'll do. If this version of the driver works with all test cases I'll
deploy a new release. I hope that we'll be available the next week. ;)

**Comment by judowalker** [comment]
Awesome thanks.

**Comment by MarkCBB** [comment]
Released a new package version (2.1.0) with MongoDB.Driver upgraded and tested.
During the following days I'll update the wiki.
Will be available for download when the package is indexed.

**Comment by judowalker** [comment]
Thanks for the quick update!

**Comment by MarkCBB** [comment]
Nuget package already available. Documentation and repository have been updated.
