### ISSUE TITLE
Question: .NET Core?

### ISSUE THREAD

**Issue by pdubb29** [MarkCBB/MongoDB-ASP.NET-Session-State-Store#12]
Are there any plans to make this project available in .NET core?

**Comment by MarkCBB** [comment]
That's a good question! I'm getting started to upgrade from .NET framework to .NET core and I saw that the approach to implement this driver should be completely different, which means that almost anything can be reused and will take some time to implement the driver.

I'll try to do a first approach/analysis on how I could implement a session state store for MongoDB in .net core and let you know in lets say.... two/three weeks.

I don't discard to do it, but honestly, I have to be sure that I can do it with the time that I have available ;)

**Comment by pdubb29** [comment]
Sounds fair, thanks!

**Comment by MarkCBB** [comment]
I know I have this conversation still pending. I already have an approach that could be a good idea, but I need a bit more time to check. I'll come back as soon as I have enough info. Sorry for being late, but didn't forget ;)

**Comment by MarkCBB** [comment]
After an initial analysis, looks like .net core uses two repositories or components to implement the session state.

First, the project aspnet/Session manages the session in the http layer and the project aspnet/Caching implements the in-memory caching and distributed caching in the data layer (in-memory, redis, SQLServer). So aspnet/Session uses the implementation of aspnet/Caching to store the data in some place.

I guess I'll have to add some implementations to these two projects to enable the session state management in MongoDB.

By the way, I think that this split in two independent components is a good analysis from Microsoft, because everything implemented in aspnet/Caching can be reused by other components, and Aspnet/session can take the benefit of any additional implementation of aspnet/Caching.

My idea is to provide some implementation as closer as possible as the implementation done by Microsoft in order to do something standard and maintainable. I'll continue taking a look and let you know.

**Comment by pdubb29** [comment]
Thanks for the update.

**Comment by MarkCBB** [comment]
I already started the implementation of Caching package in this branch https://github.com/MarkCBB/Caching/tree/feature/caching-mongodb
**First implemented test case was OK!** I could insert and delete some data in a MongoDB database.
Let's continue progressing!

**Comment by MarkCBB** [comment]
I'm still implementing the caching package at the same time that I'm understanding what I have to code by reading the existing implementations for SqlServer and Redis. I'm in a quite good pace and I think will be able to have a development package in a month. Next, I'll have to discover the package [Session](https://github.com/aspnet/Session) and how to make it works with the added implementation of cache.

I'll keep this question up to date.

**Comment by MarkCBB** [comment]
Still work in progress. I'll announce the first development version of the packages when I push them to nuget. To stay up to date about the work that is being done you can watch this branch: https://github.com/MarkCBB/Caching/commits/feature/caching-mongodb

**Comment by MarkCBB** [comment]
I've uploaded [this nuget package](https://www.nuget.org/packages/MarkCBB.Extensions.Caching.MongoDB/) which is a preview for the cache implementation for MongoDB. Now, is time to make an implementation based on the [session package](https://github.com/aspnet/Session) to consume the new cache implementation.

**Comment by MarkCBB** [comment]
Finally, I'm almost sure that no change will be needed in the session package to enable this mongoDB caching.

The last release should be quite stable. @pdubb29, I would really appreciate if you can test it and give me some feedback.

To make it run you can follow these steps: https://github.com/MarkCBB/Caching/wiki#usage

> Do not rely on the index creation feature because probably will be removed. I'll go for an implementation in a package for tooling or for a complete documentation in the wiki on how to do a performance tunning in mongoDB.

**Comment by MarkCBB** [comment]
I could test this project in an ASP.NET core site without any change in the package aspnet/Session.

In the [wiki](https://github.com/MarkCBB/Caching/wiki) you'll find documentation about how to get started, best practices for performance tuning and all available settings.

A release candidate of this package is already available [in this nuget repo](https://www.nuget.org/packages/MarkCBB.Extensions.Caching.MongoDB).

So far, this conversation was useful to follow the status of the initial implementation, but as of now to follow the updates you can check [the nuget repo itself](https://www.nuget.org/packages/MarkCBB.Extensions.Caching.MongoDB), [the wiki](https://github.com/MarkCBB/Caching/wiki) or [the repo](https://github.com/MarkCBB/Caching).

I'll close this conversation right now, for any additional issue please refer to the [issue tracker](https://github.com/MarkCBB/Caching/issues) of the repo.
