### ISSUE TITLE
Update Newtonsoft.Json to latest version

### ISSUE THREAD

**Issue by judowalker** [MarkCBB/MongoDB-ASP.NET-Session-State-Store#2]
I'm using the latest Newtonsoft.Json (7.0.1) in my project which prevents me from installing your package. Can you update your package to use, or at least allow, the latest Newtonsoft.Json?

**Comment by MarkCBB** [comment]
I'm considering to remove the json serialization because it's quite useless. If so I can deploy a new major version without json compatibility and also without json dependency (as is planned). I can do it in a few days. Are you using the json serialization to serialize session data?

**Comment by judowalker** [comment]
No I'm just using it for other things in my project but it's blocking me from installing your package since I'm using the latest version of Newtonsoft.Json.
Thanks.

**Comment by MarkCBB** [comment]
A release candidate package has been uploaded in NuGet. Meanwhile I'm doing the final tests and updating the documentation, please could you test this new release candidate?
Here you'll find it:
https://www.nuget.org/packages/MongoSessionStateStore/3.0.0-rc

**Comment by judowalker** [comment]
I was able to install it now that you removed the Newtonsoft.Json dependency. Thanks.

**Comment by MarkCBB** [comment]
The definitive package version 3.0.0 has been uploaded to NuGet. Could take few time to be indexed and available for download.
