### ISSUE TITLE
Allow ApplicationName to be configurable

### ISSUE THREAD

**Issue by K2saint** [MarkCBB/MongoDB-ASP.NET-Session-State-Store#3]
Hi mate, would you consider making the _applicationName to be configuration driven via sessionstate configuration element? 

``` C#
_applicationName = "Sessions";
            var applicationNameStr = this.GetConfigVal(config, "applicationName");
            if (!string.IsNullOrEmpty(applicationNameStr))
                _applicationName = applicationNameStr;
```

**Comment by MarkCBB** [comment]
I'm running the test cases in a new branch.

**Comment by MarkCBB** [comment]
Released a new version in NuGet that enables to set a personalized application name.
Now you can share the session data across different applications. Please note that, even that it's quite difficult and improbable, a sessionId collision could occur between different applications. Also, you'll must set the same application name in the web.config in each application.
If you'll find any problem let me know. I'll close this issue between today and tomorrow.
