### ISSUE TITLE
Request - Remove need for MongoSessionHelpers by not serializing session items as BsonValue

### ISSUE THREAD

**Issue by judowalker** [MarkCBB/MongoDB-ASP.NET-Session-State-Store#5]
Currently with your implementation we have to retrieve session items as follows:

``` c#
var myAnimal = Session.Mongo<Animal>("MyAnimal");
```

We have a lot of web applications that use session and it would be very tedious to change all references of `Session[]` to `Session.Mongo<>`. Another reason we can't do this is because all our developers will have to use this new convention. It would be easy for a developer to forget or for future developers to not know this convention.

We are currently using an older implementation of a MongoDb session state provider which stores the actual serialized value instead of `BsonValue`. This allows us to use this convention:

``` c#
var myAnimal = (Animal)Session["MyAnimal"];
```

Since we share session across web applications, we have some logic in place when attempting to deserialize a session item of a type that the application doesn't know about. In this case we just store the serialized value as the session item so that it can be written back to MongoDb.

For example, here is our Serialize and Deserialize methods which are called in `SetAndReleaseItemExclusive()`, `GetItem()`, and `GetItemExclusive()`:

``` c#
private Dictionary<string, string> Serialize(SessionStateItemCollection items) {
    var serializedItems = new Dictionary<string, string>(items.Count);
    foreach (string key in items.Keys) {
        var item = items[key];
        if (item is UnSerializedItem) {
            var tmp = item as UnSerializedItem;
            serializedItems.Add(key, tmp.SerializedString);
        }
        else if (item != null) {
            using (var ms = new MemoryStream()) {
                IFormatter formatter = new BinaryFormatter();
                formatter.Serialize(ms, item);
                var serializedItem = Convert.ToBase64String(ms.ToArray());
                serializedItems.Add(key, serializedItem);
            }
        }
    }
    return serializedItems;
}
```

``` c#
private SessionStateStoreData Deserialize(HttpContext context, BsonDocument serializedItems, int timeout) {
    var sessionItems = new SessionStateItemCollection();
    foreach (var element in serializedItems) {
        try {
            using (var ms = new MemoryStream(Convert.FromBase64String(element.Value.AsString))) {
                IFormatter formatter = new BinaryFormatter();
                var item = formatter.Deserialize(ms);
                sessionItems[element.Name] = item;
            }
        }
        catch (SerializationException) {
            sessionItems[element.Name] = new UnSerializedItem {SerializedString = element.Value.AsString};
        }

    }
    return new SessionStateStoreData(sessionItems,
                                     SessionStateUtility.GetSessionStaticObjects(context),
                                     timeout);
}
```

Would it be possible for you to implement something like this? If so that would be great and we can install your nuget package for all our web applications.

Thanks.

**Comment by MarkCBB** [comment]
Looks nice! Let me some time to finish the other opened issue (#4) and I'll try to include this serialization. I've to think about how to do it. The idea to serialize as BSonValue is to use the default or closest data type that Mongo uses. But to use additional ways to serialize -if those are useful- always is a plus. Have you some suggestion to name this type of serialization?

**Comment by judowalker** [comment]
Maybe direct serialization or raw value serialization. Another benefit of this is that what you put in session is exactly what you get back after deserialization. A side-effect of your implementation is that
`Session["MyAnimal"]` before serialization to the store does not equal `Session["MyAnimal"]` after deserialization from the store.

**Comment by MarkCBB** [comment]
Sounds good, next week I'll work on it!
Meantime, happy new year!

**Comment by judowalker** [comment]
Thanks. Happy New Year to you too. :fireworks:

**Comment by MarkCBB** [comment]
Hi @judowalker ,
Diving into all the possibilities with nullables seems that the other issue (#4) will take me longer time to find out a solution (or even define formal limitations throwing exceptions). So finally I've decided to proceed with this issue before than the previous. Also, this issue will add more valuable functionality.

About this issue, I have three questions about your sample:
- First, all the classes that you are serializing are marked with the attribute `[Serializable]` ?
- And second, I understand that the class named UnSerializedItem that you are using in the serialize method is not a standard class of .NET framework. Am I right? 

I've done an initial implementation with a few test cases (all passed, although not automated yet). In this implementation I've not needed the condition `if (item is UnSerializedItem)` and I'm pretty sure that I won't need it in this implementation. You'll find the raw serialize and deserialize methods in the recently created class [RawSerialization](https://github.com/MarkCBB/MongoDB-ASP.NET-Session-State-Store/blob/Branch_raw_serialization/MongoSessionStateStore/Serialization/RawSerialization.cs). 
- You'll know better than I this implementation, so could you confirm that I'm right in the assumption that I won't need the code inside the detailed if?

And also, if possible and you want, could you clone the branch Branch_raw_serialization and test it? Note that the test cases are implemented in the project TestApplication_RAWSerialization. I'll be glad to know your feedback.

Regards,

Marc.

**Comment by judowalker** [comment]
Yes they would need to be marked as `[Serializable]`.

Yes `UnSerializedItem` is a custom class that contains the serialized string. I'm not too fond of the name since it's confusing.

The tests pass because they know the type that the string is deserialized to. This won't work across applications if the other application doesn't know the type. In this case, the serialized string is stored in session as is so that it can be written back to the database. This is a common use case for us since we share session across multiple applications but not all applications will know the types that are stored in session.

**Comment by judowalker** [comment]
@MarkCBB any thoughts on how you want to handle the scenario I mentioned?

**Comment by MarkCBB** [comment]
Sorry, I'm in a middle of an app rollout at my job, so I'll be busy a few days. I'll try to be back to this during at the end of next week.

**Comment by MarkCBB** [comment]
I think that I’ve found a solution that makes it simply and -the most important- it’s based in the standard C# features.

With the serialization/deserialization code as it is, working with a dynamic var you can work with deserialized objects whose type is unknown.

This solution it’s a native .NET feature that could cover all of your needs. Also you won’t need to train your developers with specific way to work with this Session provider. 

Please, take a look to the test case available in the Index method in the [GetWithoutTypeController](https://github.com/MarkCBB/MongoDB-ASP.NET-Session-State-Store/blob/Branch_raw_serialization/TestApplication_RAWSerialization/Controllers/GetWithoutTypeController.cs). This controller doesn’t have any reference to the serialized types (Person and PersonPetsList) but is able to get objects of those types and work with them. As you will see all vars are declared as a dynamic. **Remember to execute the method GetAndSetSameRequestObjects in the HomeController before than to call the Index in the GetWithoutTypeController** in order to set the values.

Let me know your feedback about that.

PS: I'm still in the middle of a rollout but I've found some time for this. I could take some time to answer.

**Comment by judowalker** [comment]
The issue is with the deserialization process, not type casting from the Session object. Your test works because the serializer and deserializer are in the same project. If you move the GetWithoutTypeController into a new mvc project and set up the Mongo session state provider, when you call Index, you'll get the following error:

```
Server Error in '/' Application.

Unable to find assembly 'TestApplication_RAWSerialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Runtime.Serialization.SerializationException: Unable to find assembly 'TestApplication_RAWSerialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Source Error: 


Line 51:                 {
Line 52:                     IFormatter formatter = new BinaryFormatter();
Line 53:                     var item = formatter.Deserialize(ms);
Line 54:                     sessionItems[name] = item;
Line 55:                 }

Source File: c:\Code\MongoDB-ASP.NET-Session-State-Store\MongoSessionStateStore\Serialization\RawSerialization.cs    Line: 53 

Stack Trace: 


[SerializationException: Unable to find assembly 'TestApplication_RAWSerialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.]
   System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly() +4819190
   System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name) +14023616
   System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable) +241
   System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record) +326
   System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run() +218
   System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage) +219
   System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage) +447
   System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream) +33
   MongoSessionStateStore.Serialization.RawSerialization.Deserialize(HttpContext context, BsonArray bsonSerializedItems, Int32 timeout) in c:\Code\MongoDB-ASP.NET-Session-State-Store\MongoSessionStateStore\Serialization\RawSerialization.cs:53
   MongoSessionStateStore.Serialization.SerializationProxy.Deserialize(HttpContext context, BsonArray bsonSerializedItems, Int32 timeout) in c:\Code\MongoDB-ASP.NET-Session-State-Store\MongoSessionStateStore\Serialization\SerializationProxy.cs:39
   MongoSessionStateStore.MongoSessionStateStoreHelpers.Deserialize(HttpContext context, BsonArray bsonSerializedItems, Int32 timeout) in c:\Code\MongoDB-ASP.NET-Session-State-Store\MongoSessionStateStore\MongoSessionStateStoreHelpers.cs:212
   MongoSessionStateStore.MongoSessionStateStore.GetSessionStoreItem(Boolean lockRecord, HttpContext context, String id, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actionFlags) in c:\Code\MongoDB-ASP.NET-Session-State-Store\MongoSessionStateStore\MongoSessionStateStore.cs:458
   MongoSessionStateStore.MongoSessionStateStore.GetItemExclusive(HttpContext context, String id, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actionFlags) in c:\Code\MongoDB-ASP.NET-Session-State-Store\MongoSessionStateStore\MongoSessionStateStore.cs:346
   System.Web.SessionState.SessionStateModule.GetSessionStateItem() +178
   System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData) +1053
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +12336334
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34274
```

**Comment by MarkCBB** [comment]
Indeed. When the dll is not there this exception is thrown. I thought that without any reference in the code was enough to reproduce it but I was wrong.
What do you think if we move to XML serialization instead of Binary?

**Comment by judowalker** [comment]
Well by default `XmlSerializer` doesn't serialize private fields/properties. Also, xml will take up more space. You could also look at https://github.com/mgravell/protobuf-net which uses protocol buffers (https://developers.google.com/protocol-buffers/). I'm not sure how easy that would be to implement with the session store provider but it's very efficient.

In the meantime, could you finish the RawSerialization implementation and handle the unknown type error (using try/catch and storing the serialized string in session)?

You could always provide choices for serialization formats for future releases.

**Comment by MarkCBB** [comment]
Yes I'll do it. Also, I’ll run the test cases using the newest version of MongoDB driver recently released (2.2.1).
Are you agree if I return an anonymous class with a property called SerializedString containing the serialized string? Something like this:

```
catch (Exception)
{
         sessionItems[name] = new { SerializedString = value };
}
```

**Comment by judowalker** [comment]
How would you then check for the serialized string to add back to the database? Why not create a simple class to store the serialized string?

**Comment by judowalker** [comment]
Also the exception you should catch is `SerializationException`.

**Comment by MarkCBB** [comment]
I was thinking in the opposite logic: _Check that the type is the type that you’re looking for and if not, you can get the serialized string using a dynamic type_. But, how can you do that if you don’t know the type? It’s better to check if the type is the unserialized class to know if the deserialization was possible. So your approach is better and I’ll create a public class.

About the exception caught, better as more detailed, so I’ll use SerializationException.

Sorry for my low attention to detail, but I’m quite full of work and I’m thinking and updating in the middle of another tasks.

If all goes as I expect in the middle of next week I'll be able to have the new release.

**Comment by MarkCBB** [comment]
Hi,
I've experienced some trouble generating the dll with the latest version of MongoDB driver and then packing the dll of this project allowing the versions 2.1.X of MongoDB driver. When the dependency resolves and downloads a driver in this version range, I got a "type not found" exception (the missing type is a method in the MongoDB driver).
To avoid this problem I'll have to limit the dependencies to versions 2.2.0 and 2.2.2. With this version range the nuget package generated works as expected.
I'm finishing the tests with the packed dll and this weekend I'll have the package.

**Comment by judowalker** [comment]
Sounds good. Thanks.

**Comment by MarkCBB** [comment]
The new release is already published in nuget. You're mentioned in [this release notes](https://github.com/MarkCBB/MongoDB-ASP.NET-Session-State-Store/wiki/Release-notes-history-and-compatibility-between-versions#v320) (if you don't want to be mentioned just let me know).

I'll keep this issue open for some days, just in case of some problem related or any feedback that you would like to write here.

It seems that you're experienced about serialization and now this package is better thanks to your proposal and comments. So, thank you and I would like to encourage you to collaborate in every thing that could improve it!

**Comment by judowalker** [comment]
Nice job! I will install it and try it out.

**Comment by judowalker** [comment]
This appears to be working correctly across multiple applications. Thanks for implementing this. The only thing I found was the nuget package is adding a `MongoSessionHelpers.cs` file to my project which can just be included in the assembly. I created another issue for that: https://github.com/MarkCBB/MongoDB-ASP.NET-Session-State-Store/issues/6

**Comment by MarkCBB** [comment]
Good!! I'm happy to know that all works as expected. About the issue #6 I've an idea to include this type in the assembly and maintaining the possibility to personalize the implementations inside the file (it's a static class and can not be extended). I'll answer there in more detail in a few days.
